import { SupabaseClient } from '@supabase/supabase-js'
import { DistressScore, DistressSignal, DistressLevel } from '../types'

export async function computeDistressScore(
  supabase: SupabaseClient,
  farmerName: string,
  district: string,
  taluka: string,
  identifier: string // e.g., Aadhaar last 4 or phone
): Promise<DistressScore> {
  let score = 0
  const signals: DistressSignal[] = []

  // 1. Rejections in last 90 days
  const ninetyDaysAgo = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString()
  const { count: rejectionCount } = await supabase
    .from('applications')
    .select('id', { count: 'exact', head: true })
    .eq('farmer_name', farmerName)
    .eq('district', district)
    .eq('status', 'rejected')
    .gte('submitted_at', ninetyDaysAgo)
    
  if (rejectionCount && rejectionCount > 0) {
    const weight = rejectionCount * 20
    score += weight
    signals.push({ type: 'recent_rejections', description: `${rejectionCount} applications rejected in last 90 days`, weight })
  }

  // 2. SLA breached unresolved grievances
  const { data: overdueGrievances } = await supabase
    .from('grievances')
    .select('id, priority')
    .eq('farmer_name', farmerName)
    .eq('district', district)
    .neq('status', 'resolved')
    .lt('sla_deadline', new Date().toISOString())
    
  if (overdueGrievances && overdueGrievances.length > 0) {
    const weight = overdueGrievances.length * 25
    score += weight
    signals.push({ type: 'sla_breach', description: `${overdueGrievances.length} unresolved grievances past SLA`, weight })
    
    // Priority 5 unresolved
    const p5Count = overdueGrievances.filter(g => g.priority === 5).length
    if (p5Count > 0) {
      const p5Weight = p5Count * 40
      score += p5Weight
      signals.push({ type: 'critical_grievance', description: `${p5Count} critical priority 5 grievances unresolved`, weight: p5Weight })
    }
  }

  // 3. Matched schemes not applied
  const { data: eligibilityChecks } = await supabase
    .from('eligibility_checks')
    .select('matched_schemes')
    .eq('farmer_name', farmerName)
    .order('checked_at', { ascending: false })
    .limit(1)
    
  if (eligibilityChecks && eligibilityChecks.length > 0 && eligibilityChecks[0].matched_schemes) {
    const matchedSchemeIds = (eligibilityChecks[0].matched_schemes as any[]).map(s => s.schemeId)
    
    const { data: existingApps } = await supabase
      .from('applications')
      .select('scheme_name')
      .eq('farmer_name', farmerName)
      
    const appliedSchemeNames = existingApps?.map(a => a.scheme_name) || []
    
    // Rough check: if they matched 3+ schemes but applied for none
    if (matchedSchemeIds.length > 0 && appliedSchemeNames.length === 0) {
      score += 15
      signals.push({ type: 'unclaimed_benefits', description: `Eligible for ${matchedSchemeIds.length} schemes but 0 applications found`, weight: 15 })
    }
  }

  // 4. Insurance stuck > 30 days
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  const { count: stuckInsurance } = await supabase
    .from('applications')
    .select('id', { count: 'exact', head: true })
    .eq('farmer_name', farmerName)
    .eq('document_type', 'insurance_claim')
    .in('status', ['pending', 'held', 'in_review'])
    .lt('submitted_at', thirtyDaysAgo)
    
  if (stuckInsurance && stuckInsurance > 0) {
    const weight = stuckInsurance * 30
    score += weight
    signals.push({ type: 'stuck_insurance', description: `${stuckInsurance} insurance claims stuck for > 30 days`, weight })
  }

  // Determine Risk Level
  let risk_level: DistressLevel = 'LOW'
  if (score >= 120) risk_level = 'CRITICAL'
  else if (score >= 70) risk_level = 'HIGH'
  else if (score >= 30) risk_level = 'MEDIUM'

  return {
    id: '', // Will be generated by DB
    farmer_identifier: identifier,
    farmer_name: farmerName,
    district,
    taluka,
    score,
    risk_level,
    signals,
    computed_at: new Date().toISOString()
  }
}
